### ISSUE TITLE
Request for help to port OpenSSL RAND_bytes() to ISAAC

### ISSUE THREAD

**Issue by LeMoussel** [edgeofmagic/ISAAC-engine#1]
I want to initialze array with random number 
I tried with RAND_bytes() from OpenSSL but it's not very efficient.

Example :
```
unsigned char nonce96[12];

RAND_poll();
for (uint32_t j = 0; j < 1000000; j++) {
	RAND_bytes(nonce96, sizeof(nonce96));
}
```

Is it possible to use your C++ Implementation of ISAAC to do this?
If so, can you give me an example?

Thank you for your help

**Comment by edgeofmagic** [comment]
I have added a function template called random_fill that will do what you want (I think):
```` cpp
template<class Generator>
inline void
random_fill(Generator& gen, unsigned char* buf, std::size_t count)
{
	static constexpr std::size_t word_size = sizeof(typename Generator::result_type);
	unsigned char* p = buf;
	unsigned char* limit = p + count;
	while (p < limit)
	{
		auto word = gen();
		auto n = std::min(static_cast<std::size_t>(limit - p), word_size);
		::memcpy(p, &word, n);
		p += n;
	}
}
````
This template will take any engine that meets the basic requirements (e,g, isaac, linear_congruential_engine, mersenne_twister_engine, etc.) as a parameter, and use that
engine to fill the buffer with random bits.  This function template is defined at line 21 of main.cpp.

Note that the function is inline, so you can put it in a header if you want without worrying about multiply-defined symbols at link time.

At the end of main() (line 67 of main.cpp) there is an example of the function's use. In isolation, it would look like this:
```` cpp
std::random_device rdev;
util::isaac64<8>  gen{rdev};
unsigned char nonce96[12];
for (uint32_t j = 0; j < 1000000; j++) {
	random_fill(gen, nonce96, sizeof(nonce96));
}
````
Please let me know if this is adequate, and I"ll close the issue.

**Comment by LeMoussel** [comment]
Yes this adequate. Thank you for your help.

One last quick question: Is it possible to store the ISAAC result in an OpenSSL BIGNUM?
With OpenSSL I do :
```
BIGNUM *rndNonce80 = BN_new();
BN_rand(rndNonce80, 80, 1, 1); // 80 => 10 Bytes * 8 bits
std::cout << "rndNonce80 = " << BN_bn2hex(rndNonce80) << std::endl;
```

**Comment by edgeofmagic** [comment]
The following function should do the trick. As you can see, it goes to some trouble to behave
like BN_rand as closely as possible. If you don't care about the top and bottom parameters, it could be simplified somewhat.
```` cpp
#include <openssl/bn.h>
#include "isaac.h"

template<class Generator>
inline int BN_rand_from_generator(Generator& gen, BIGNUM *big_result, int bits, int top, int bottom)
{
	constexpr int success = 1;
	constexpr int failure = 0;

	int result{success};

	if (!big_result || (bits < 0) || (bits == 1 && top > 0)) 
	{
		result = failure; 
	}
	else if (bits == 0)
	{
		BN_zero(big_result);
	}
	else
	{
		std::size_t nbytes = bits / 8;
		if (bits % 8) ++nbytes;
		unsigned char random_bytes[nbytes];
		random_fill(gen, random_bytes, nbytes);
		BN_bin2bn(random_bytes, nbytes, big_result);

		// truncate if bits doesn't divide evenly by 8
		if (bits % 8)
		{
			BN_mask_bits(big_result, bits); 
		}
		
		// enforce top and bottom constraints
		// assert(bits > 0 && (top < 1 || bits > 1));
		if (top >= 0) BN_set_bit(big_result, bits - 1); 
		if (top > 0) BN_set_bit(big_result, bits - 2); 
		if (bottom) BN_set_bit(big_result, 0);
	}
	return result;
}
````
To use it, do something like this:

```` cpp
std::random_device rdev;
utils::isaac64<> gen{rdev};
BIGNUM *rndNonce80 = BN_new();
BN_rand_from_generator(gen, rndNonce80, 80, 1, 1);
std::cout << "rndNonce80 = " << BN_bn2hex(rndNonce80) << std::endl;
````
BN_rand_from_generator is a function template, so it can take any suitable random generator as its first parameter (including isaac).
